<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Rays.Plugins.WPF" Version="1.1.37.1010" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NKnife.Circe.Common\NKnife.Circe.Common.csproj" />
    <ProjectReference Include="..\NKnife.Circe.Theme\NKnife.Circe.Theme.csproj" />
  </ItemGroup>

</Project>
