//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NKnife.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OwnResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OwnResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NKnife.Properties.OwnResources", typeof(OwnResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;nlog xmlns=&quot;http://www.nlog-project.org/schemas/NLog.xsd&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;extensions&gt;
        ///    &lt;add assembly=&quot;NKnife.NLog3&quot; /&gt;
        ///  &lt;/extensions&gt;
        ///  &lt;targets async=&quot;true&quot;&gt;
        ///    &lt;!--在主程序的界面上显示日志--&gt;
        ///    &lt;target name=&quot;logpanel&quot; xsi:type=&quot;LogPanel&quot; /&gt;
        ///    &lt;!--记录详细日志彩色控制台--&gt;
        ///    &lt;target name=&quot;console&quot; xsi:type=&quot;ColoredConsole&quot; layout=&quot;${date:format=mm\:ss\.fff} : ${message}&quot; /&gt;
        ///  &lt;/targets&gt;
        ///  &lt;rules&gt;
        ///    &lt;logger name=&quot;*&quot; minLev [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string nlog_winform_config {
            get {
                return ResourceManager.GetString("nlog_winform_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;nlog xmlns=&quot;http://www.nlog-project.org/schemas/NLog.xsd&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;extensions&gt;
        ///    &lt;add assembly=&quot;NKnife.NLog3&quot; /&gt;
        ///  &lt;/extensions&gt;
        ///  &lt;targets async=&quot;true&quot;&gt;
        ///    &lt;!--在主程序的界面上显示日志--&gt;
        ///    &lt;target name=&quot;wpf_logger_collection&quot; xsi:type=&quot;Log_Collection&quot; /&gt;
        ///    &lt;!--记录详细日志彩色控制台--&gt;
        ///    &lt;target name=&quot;console&quot; xsi:type=&quot;ColoredConsole&quot; layout=&quot;${date:format=mm\:ss\.fff} : ${message}&quot; /&gt;
        ///  &lt;/targets&gt;
        ///  &lt;rules&gt;
        ///    &lt;log [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string nlog_wpf_config {
            get {
                return ResourceManager.GetString("nlog_wpf_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon NLogForm {
            get {
                object obj = ResourceManager.GetObject("NLogForm", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
