<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Internal\App-Welcome-old.png" />
    <None Remove="Internal\App-Welcome.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Mercury\Common\RAY.Plugins.WPF\RAY.Plugins.WPF.csproj" />
    <ProjectReference Include="..\..\NKnife.Circe.Base\NKnife.Circe.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Internal\App-Welcome.png" />
  </ItemGroup>

</Project>
