<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <SatelliteResourceLanguages>en;zh-Hans;zh-Hant</SatelliteResourceLanguages>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <ApplicationIcon>App.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="App.ico" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Mercury\Addins\LEIAO.Addin.PerformanceDetector\LEIAO.Addin.PerformanceDetector.csproj" />
        <ProjectReference Include="..\..\Mercury\Addins\LEIAO.Addin.StatusBasicInfo\LEIAO.Addin.StatusBasicInfo.csproj" />
        <ProjectReference Include="..\..\Mercury\Common\RAY.Commlink\RAY.Commlink.csproj" />
        <ProjectReference Include="..\..\Mercury\Common\RAY.Common\RAY.Common.csproj" />
        <ProjectReference Include="..\..\Mercury\Common\RAY.Library\RAY.Library.csproj" />
        <ProjectReference Include="..\..\Mercury\Common\RAY.Plugins.WPF\RAY.Plugins.WPF.csproj" />
        <ProjectReference Include="..\..\Mercury\Common\RAY.Plugins\RAY.Plugins.csproj" />
        <ProjectReference Include="..\..\Mercury\Common\RAY.Storages\RAY.Storages.csproj" />
        <ProjectReference Include="..\..\Mercury\Common\RAY.Windows\RAY.Windows.csproj" />
        <ProjectReference Include="..\..\Mercury\Features\LEIAO.Feature.PluginBrowser\LEIAO.Feature.PluginBrowser.csproj" />
        <ProjectReference Include="..\..\Mercury\Modules\LEIAO.Module.Messenger\LEIAO.Module.Messenger.csproj" />
        <ProjectReference Include="..\Features\NKnife.Feature.ConnectorManager\NKnife.Feature.ConnectorManager.csproj" />
        <ProjectReference Include="..\Features\NKnife.Feature.ExperimentManager\NKnife.Feature.ExperimentManager.csproj" />
        <ProjectReference Include="..\Features\NKnife.Feature.InstrumentManager\NKnife.Feature.InstrumentManager.csproj" />
        <ProjectReference Include="..\Features\NKnife.Feature.LogService\NKnife.Feature.LogService.csproj" />
        <ProjectReference Include="..\Features\NKnife.Feature.PreferenceService\NKnife.Feature.PreferenceService.csproj" />
        <ProjectReference Include="..\Features\NKnife.Feature.UutManager\NKnife.Feature.UutManager.csproj" />
        <ProjectReference Include="..\Features\NKnife.Feature.Welcome\NKnife.Feature.Welcome.csproj" />
        <ProjectReference Include="..\Modules\Data\NKnife.Module.Data.Databases\NKnife.Module.Data.Databases.csproj" />
        <ProjectReference Include="..\Modules\Data\NKnife.Module.Data.ProviderFactory\NKnife.Module.Data.ProviderFactory.csproj" />
        <ProjectReference Include="..\Modules\Data\NKnife.Module.Data.Repository\NKnife.Module.Data.Repository.csproj" />
        <ProjectReference Include="..\Modules\Data\NKnife.Module.Data.Storages\NKnife.Module.Data.Storages.csproj" />
        <ProjectReference Include="..\Modules\Managers\NKnife.Module.ConnectorManager\NKnife.Module.ConnectorManager.csproj" />
        <ProjectReference Include="..\Modules\Managers\NKnife.Module.ExperimentManager\NKnife.Module.ExperimentManager.csproj" />
        <ProjectReference Include="..\Modules\Managers\NKnife.Module.InstrumentManager\NKnife.Module.InstrumentManager.csproj" />
        <ProjectReference Include="..\Modules\Managers\NKnife.Module.UutManager\NKnife.Module.UutManager.csproj" />
        <ProjectReference Include="..\Modules\NKnife.Module.Mock\NKnife.Module.Mock.csproj" />
        <ProjectReference Include="..\Modules\NKnife.Module.Workbench\NKnife.Module.Workbench.csproj" />
        <ProjectReference Include="..\Modules\Services\NKnife.Module.AppWorkspaceService\NKnife.Module.AppWorkspaceService.csproj" />
        <ProjectReference Include="..\Modules\Services\NKnife.Module.LogService\NKnife.Module.LogService.csproj" />
        <ProjectReference Include="..\Modules\Services\NKnife.Module.PreferenceService\NKnife.Module.PreferenceService.csproj" />
        <ProjectReference Include="..\Modules\Services\NKnife.Module.WelcomeService\NKnife.Module.WelcomeService.csproj" />
        <ProjectReference Include="..\NKnife.Circe.Base\NKnife.Circe.Core.csproj" />
        <ProjectReference Include="..\NKnife.Circe.Domain\NKnife.Circe.Domain.csproj" />
        <ProjectReference Include="..\NKnife.Circe.Theme\NKnife.Circe.Theme.csproj" />
    </ItemGroup>

</Project>